This commit fixes a BPF filter problem.
Problem:
macOS on M1 Mac produces a BPF error with the following code:
from scapy.all import *
sniff(iface="en0", filter="", prn=lambda p:p)

The error traceback is like this:
Traceback (most recent call last):
  File "bpferror.py", line 2, in <module>
    sniff(iface="en0", filter="", prn=lambda p:p)
  File "/Users/ikawamoto/.pyenv/versions/3.9.6/lib/python3.9/site-packages/scapy/sendrecv.py", line 1263, in sniff
    sniffer._run(*args, **kwargs)
  File "/Users/ikawamoto/.pyenv/versions/3.9.6/lib/python3.9/site-packages/scapy/sendrecv.py", line 1127, in _run
    sniff_sockets[L2socket(type=ETH_P_ALL, iface=iface,
  File "/Users/ikawamoto/.pyenv/versions/3.9.6/lib/python3.9/site-packages/scapy/arch/bpf/supersocket.py", line 254, in __init__
    super(L2bpfListenSocket, self).__init__(*args, **kwargs)
  File "/Users/ikawamoto/.pyenv/versions/3.9.6/lib/python3.9/site-packages/scapy/arch/bpf/supersocket.py", line 119, in __init__
    attach_filter(self.ins, filter, self.iface)
  File "/Users/ikawamoto/.pyenv/versions/3.9.6/lib/python3.9/site-packages/scapy/arch/bpf/core.py", line 155, in attach_filter
    raise Scapy_Exception("Can't attach the BPF filter !")
scapy.error.Scapy_Exception: Can't attach the BPF filter !

Cause of this issue:
This error is brought by an ioctl call of the previous line,
  core.py:153:    ret = LIBC.ioctl(c_int(fd), BIOCSETF, cast(pointer(bp), c_char_p))
and this ioctl succeed with some other environment, intel mac or intel/arm linuxes.
This patch changes the stack frames of calling ioctl correctly.